apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: packetbeat-daemonset 
  name: packetbeat-daemonset 
spec:
  selector:
    matchLabels:
      app: packetbeat-daemonset 
  template:
    metadata:
      labels:
        app: packetbeat-daemonset 
    spec:
      serviceAccountName: packetbeat-dynamic
      terminationGracePeriodSeconds: 30
      containers:
      - image: docker.elastic.co/beats/packetbeat:7.9.1
        name: packetbeat
        imagePullPolicy: Always
        args: [
          "-c", "/etc/packetbeat.yml",
          "-e",
        ]
        securityContext:
            runAsUser: 0
            capabilities:
              add:
              - NET_ADMIN
        env:
        - name: ELASTICSEARCH_HOSTS
          value: http://elasticsearch-master:9200
        - name: SERVER_HOST
          value: 0.0.0.0
        - name: NODE_OPTIONS
          value: --max-old-space-size=1800
        volumeMounts:
        - name: config
          mountPath: /etc/packetbeat.yml
          readOnly: true
          subPath: packetbeat.yml
        - name: data
          mountPath: /usr/share/packetbeat/data
      volumes:
      - name: config
        configMap:
          defaultMode: 0600
          name: packetbeat-config
      - name: data
        emptyDir: {}
                